`nom` varchar(255) NOT NULL,
`description` varchar(255) DEFAULT NULL,
`type` varchar(255) NOT NULL,
`chemin` varchar(255) DEFAULT NULL,
`image` varchar(255) DEFAULT NULL,
`id_map` varchar(255) DEFAULT NULL,
`map_active` tinyint(4) DEFAULT NULL,
`map_officielle` tinyint(4) DEFAULT NULL,
`mod_actif` tinyint(4) DEFAULT NULL,
`vehicule_type` varchar(255) DEFAULT NULL,
`car_type` varchar(255) DEFAULT NULL,
`archive` varchar(255) DEFAULT NULL,
`link` text DEFAULT NULL,
`date` datetime DEFAULT current_timestamp(),
PRIMARY KEY (`nom`),
UNIQUE KEY `chemin` (`chemin`),
UNIQUE KEY `image` (`image`),
UNIQUE KEY `id_map` (`id_map`),
UNIQUE KEY `archive` (`archive`)

